language: python
python:
  - "2.7"
virtualenv:
    system_site_packages: true
before_install:
    - sudo apt-get update -qq ; fi
    - sudo apt-get install -qq python-scipy python-nose python-pip ; fi
install: "pip install -r requirements.txt"
script: nosetests
